<?php
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CVController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\ApplicantController;
use App\Http\Controllers\JobReviewController;
use App\Http\Controllers\JobRequestController;
Auth::routes();
Route::get('/', [HomeController::class, 'index']);
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/contact', [ContactController::class, 'index'])->name('contact');
Route::post('/contact/store', [ContactController::class, 'store'])->name('contact.store');
Route::get('/showRequestForm', [JobRequestController::class, 'showRequestForm'])->name('JobRequest');
Route::post('/job-request/submit', [JobRequestController::class, 'submit'])->name('job-request.submit');
Route::get('job-requests', [JobRequestController::class, 'index'])->name('job-requests.index');
Route::get('job-cv/{id}', [JobRequestController::class, 'submit'])->name('jobcv');
Route::get('/JobReview', [JobReviewController::class, 'JobReview'])->name('JobReview');
Route::get('/improveCV', [CVController::class, 'showimprove'])->name('showimprove')->middleware('log');
Route::get('/messages', [MessageController::class, 'index'])->name('messages.index');
Route::post('/company', [CompanyController::class, 'store'])->name('company.store');
Route::get('/showRequestForm1', [CompanyController::class, 'show'])->name('companycreate');
Route::get('/show', [CompanyController::class, 'go'])->name('company1')->middleware('company');
Route::get('/companies', [CompanyController::class, 'index'])->name('companies.index');
Route::post('/improve-cv', [CVController::class, 'improve'])->name('cv.improve');
Route::get('/cv-requests', [CVController::class, 'listCVRequests'])->name('cv-requests');
Route::post('/applicant/store',[ApplicantController::class, 'store'] )->name('applicant.store');
Route::get('/applicant/show',[ApplicantController::class, 'show'] )->name('applicant.show');
